name: CI

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.14"

      - uses: arduino/setup-task@v2

      - run: task ci
